"""
Purpose:
    Generates TypeScript interfaces/types from Pydantic schemas to establish explicit schema contracts.
Inputs:
    None.
Outputs:
    Writes frontend/types/api_schemas.ts file.
"""
import enum
import os
from datetime import date, datetime
from typing import Union, List, Optional, Any
from types import UnionType
from pydantic import BaseModel

# Ensure DATABASE_URL is set before importing app modules
os.environ["DATABASE_URL"] = "sqlite:///:memory:"

from app.models.invoice import InvoiceWorkflowStatus
from app.models.purchase_order import PurchaseOrderStatus
from app.schemas.invoice import (
    InvoiceCreate,
    InvoiceUpdate,
    InvoiceResponse,
    InvoiceItemCreate,
    InvoiceItemResponse,
)
from app.schemas.purchase_order import (
    PurchaseOrderCreate,
    PurchaseOrderUpdate,
    PurchaseOrderResponse,
)
from app.schemas.audit_log import (
    AuditLogCreate,
    AuditLogResponse,
)

def map_type(py_type) -> str:
    if py_type is None or py_type is type(None):
        return "null"
    
    origin = getattr(py_type, "__origin__", None)
    args = getattr(py_type, "__args__", None)
    
    # In python 3.10+, we can use UnionType
    is_union = (origin is Union) or (UnionType is not None and isinstance(py_type, UnionType))
    
    if is_union:
        ts_types = []
        is_nullable = False
        for arg in args:
            if arg is type(None):
                is_nullable = True
            else:
                ts_types.append(map_type(arg))
        
        union_str = " | ".join(sorted(list(set(ts_types))))
        if is_nullable:
            union_str += " | null"
        return union_str
        
    if origin is list or origin is List:
        return f"{map_type(args[0])}[]"
        
    if py_type is str:
        return "string"
    if py_type is int or py_type is float:
        return "number"
    if py_type is bool:
        return "boolean"
    if py_type is date or py_type is datetime:
        return "string"
    if py_type is Any:
        return "any"
        
    if isinstance(py_type, type) and issubclass(py_type, enum.Enum):
        return py_type.__name__
        
    if isinstance(py_type, type) and issubclass(py_type, BaseModel):
        return py_type.__name__
        
    return "any"

def generate_enum(enum_class):
    lines = [
        f"export enum {enum_class.__name__} {{"
    ]
    for member in enum_class:
        lines.append(f'  {member.name} = "{member.value}",')
    lines.append("}\n")
    return "\n".join(lines)

def generate_interface(model_class):
    lines = [
        f"export interface {model_class.__name__} {{"
    ]
    for field_name, field_info in model_class.model_fields.items():
        py_type = field_info.annotation
        ts_type = map_type(py_type)
        
        is_required = field_info.is_required()
        opt_suffix = "" if is_required else "?"
        
        lines.append(f"  {field_name}{opt_suffix}: {ts_type};")
    lines.append("}\n")
    return "\n".join(lines)

def main():
    enums = [InvoiceWorkflowStatus, PurchaseOrderStatus]
    models = [
        InvoiceItemCreate,
        InvoiceItemResponse,
        InvoiceCreate,
        InvoiceUpdate,
        InvoiceResponse,
        PurchaseOrderCreate,
        PurchaseOrderUpdate,
        PurchaseOrderResponse,
        AuditLogCreate,
        AuditLogResponse,
    ]
    
    output = []
    output.append("/**")
    output.append(" * AUTO-GENERATED FILE. DO NOT MODIFY DIRECTLY.")
    output.append(" * Generated by: backend/app/utils/generate_ts_types.py")
    output.append(" */\n")
    
    for en in enums:
        output.append(generate_enum(en))
        
    for model in models:
        output.append(generate_interface(model))
        
    # Write to target location in frontend
    current_dir = os.path.dirname(os.path.abspath(__file__))
    root_dir = os.path.abspath(os.path.join(current_dir, "..", "..", ".."))
    frontend_types_dir = os.path.join(root_dir, "frontend", "types")
    
    os.makedirs(frontend_types_dir, exist_ok=True)
    
    output_path = os.path.join(frontend_types_dir, "api_schemas.ts")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(output))
        
    print(f"Successfully generated TypeScript schemas at: {output_path}")

if __name__ == "__main__":
    main()
