"""add_must_change_password_to_user

Revision ID: 97377f56bfd1
Revises: 012_add_po_match_tolerances
Create Date: 2026-07-26 12:03:48.606439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97377f56bfd1'
down_revision = '012_add_po_match_tolerances'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_cols = {c["name"] for c in inspector.get_columns("users")}
    if "must_change_password" not in existing_cols:
        op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
