"""add_reviewer_checklist_and_confidence

Revision ID: ba776327f7b2
Revises: 016_add_reviewer_assignment
Create Date: 2026-07-31 14:33:07.821979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba776327f7b2'
down_revision = '016_add_reviewer_assignment'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = set(inspector.get_table_names())
    
    if 'payment_gateway_configs' not in tables:
        op.create_table('payment_gateway_configs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), nullable=False),
        sa.Column('credentials', sa.JSON(), nullable=False),
        sa.Column('timeout_seconds', sa.Integer(), nullable=False),
        sa.Column('supported_currencies', sa.JSON(), nullable=False),
        sa.Column('daily_limit', sa.Float(), nullable=False),
        sa.Column('test_status', sa.String(), nullable=False),
        sa.Column('last_tested_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_payment_gateway_configs_id'), 'payment_gateway_configs', ['id'], unique=False)
        op.create_index(op.f('ix_payment_gateway_configs_name'), 'payment_gateway_configs', ['name'], unique=True)
    if 'erp_sync_logs' in tables:
        op.drop_index(op.f('ix_erp_sync_logs_erp_system'), table_name='erp_sync_logs')
        op.drop_index(op.f('ix_erp_sync_logs_id'), table_name='erp_sync_logs')
        op.drop_index(op.f('ix_erp_sync_logs_invoice_id'), table_name='erp_sync_logs')
        op.drop_index(op.f('ix_erp_sync_logs_sync_status'), table_name='erp_sync_logs')
        op.drop_table('erp_sync_logs')
    if 'org_api_keys' in tables:
        op.drop_index(op.f('ix_org_api_keys_id'), table_name='org_api_keys')
        op.drop_index(op.f('ix_org_api_keys_org_id'), table_name='org_api_keys')
        op.drop_index(op.f('ix_org_api_keys_provider_name'), table_name='org_api_keys')
        op.drop_table('org_api_keys')
    if 'gst_hsn_rules' in tables:
        op.drop_index(op.f('ix_gst_hsn_rules_hsn_prefix'), table_name='gst_hsn_rules')
        op.drop_index(op.f('ix_gst_hsn_rules_id'), table_name='gst_hsn_rules')
        op.drop_index(op.f('ix_gst_hsn_rules_organization_id'), table_name='gst_hsn_rules')
        op.drop_index(op.f('ix_gst_hsn_rules_rule_type'), table_name='gst_hsn_rules')
    invoice_cols = {c["name"] for c in inspector.get_columns("invoices")}
    payment_sched_cols = {c["name"] for c in inspector.get_columns("payment_schedules")} if 'payment_schedules' in tables else set()
    payment_txn_cols = {c["name"] for c in inspector.get_columns("payment_transactions")} if 'payment_transactions' in tables else set()
    settings_cols = {c["name"] for c in inspector.get_columns("settings")} if 'settings' in tables else set()

    if 'reviewer_checklist_completed' not in invoice_cols:
        op.add_column('invoices', sa.Column('reviewer_checklist_completed', sa.JSON(), nullable=True))
    if 'reviewer_confidence_before' not in invoice_cols:
        op.add_column('invoices', sa.Column('reviewer_confidence_before', sa.Float(), nullable=True))
    if 'reviewer_confidence_after' not in invoice_cols:
        op.add_column('invoices', sa.Column('reviewer_confidence_after', sa.Float(), nullable=True))
    if 'review_duration_seconds' not in invoice_cols:
        op.add_column('invoices', sa.Column('review_duration_seconds', sa.Integer(), nullable=True))
    
    # op.alter_column('invoices', 'workflow_status',
    #            existing_type=sa.VARCHAR(length=18),
    #            type_=sa.Enum('validation_pending', 'validation_failed', 'pending_review', 'pending_approval', 'approved', 'rejected', 'released_for_payment', 'paid', 'payment_queue', 'scheduled', 'payment_processing', 'payment_completed', name='invoiceworkflowstatus'),
    #            existing_nullable=False)
    
    # Skip index creation if it exists
    invoices_indexes = {idx["name"] for idx in inspector.get_indexes("invoices")}
    if 'ix_invoices_assigned_reviewer_id' not in invoices_indexes:
        op.create_index(op.f('ix_invoices_assigned_reviewer_id'), 'invoices', ['assigned_reviewer_id'], unique=False)
        
    if 'priority' not in payment_sched_cols:
        op.add_column('payment_schedules', sa.Column('priority', sa.String(), nullable=True))
    if 'risk_level' not in payment_sched_cols:
        op.add_column('payment_schedules', sa.Column('risk_level', sa.String(), nullable=True))
    if 'payment_method' not in payment_sched_cols:
        op.add_column('payment_schedules', sa.Column('payment_method', sa.String(), nullable=True))
    if 'erp_status' not in payment_sched_cols:
        op.add_column('payment_schedules', sa.Column('erp_status', sa.String(), nullable=True))
    if 'assigned_user' not in payment_sched_cols:
        op.add_column('payment_schedules', sa.Column('assigned_user', sa.String(), nullable=True))
    if 'expected_date' not in payment_sched_cols:
        op.add_column('payment_schedules', sa.Column('expected_date', sa.Date(), nullable=True))
    if 'gateway_name' not in payment_sched_cols:
        op.add_column('payment_schedules', sa.Column('gateway_name', sa.String(), nullable=True))
    if 'audit_history' not in payment_sched_cols:
        op.add_column('payment_schedules', sa.Column('audit_history', sa.JSON(), nullable=True))
        
    if 'gateway_response' not in payment_txn_cols:
        op.add_column('payment_transactions', sa.Column('gateway_response', sa.JSON(), nullable=True))
        
    if 'reviewer_mandatory_review_rules' not in settings_cols:
        op.add_column('settings', sa.Column('reviewer_mandatory_review_rules', sa.JSON(), nullable=True))
    if 'reviewer_auto_routing' not in settings_cols:
        op.add_column('settings', sa.Column('reviewer_auto_routing', sa.Boolean(), nullable=True))
    if 'reviewer_checklist_items' not in settings_cols:
        op.add_column('settings', sa.Column('reviewer_checklist_items', sa.JSON(), nullable=True))
    if 'reviewer_comment_requirements' not in settings_cols:
        op.add_column('settings', sa.Column('reviewer_comment_requirements', sa.JSON(), nullable=True))
    if 'reviewer_return_to_vendor_enabled' not in settings_cols:
        op.add_column('settings', sa.Column('reviewer_return_to_vendor_enabled', sa.Boolean(), nullable=True))
    if 'reviewer_edit_permissions' not in settings_cols:
        op.add_column('settings', sa.Column('reviewer_edit_permissions', sa.JSON(), nullable=True))
        
    settings_indexes = {idx["name"] for idx in inspector.get_indexes("settings")}
    if 'ix__alembic_tmp_settings_organization_id' in settings_indexes:
        op.drop_index(op.f('ix__alembic_tmp_settings_organization_id'), table_name='settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix__alembic_tmp_settings_organization_id'), 'settings', ['organization_id'], unique=False)
    op.drop_column('settings', 'reviewer_edit_permissions')
    op.drop_column('settings', 'reviewer_return_to_vendor_enabled')
    op.drop_column('settings', 'reviewer_comment_requirements')
    op.drop_column('settings', 'reviewer_checklist_items')
    op.drop_column('settings', 'reviewer_auto_routing')
    op.drop_column('settings', 'reviewer_mandatory_review_rules')
    op.drop_column('payment_transactions', 'gateway_response')
    op.drop_column('payment_schedules', 'audit_history')
    op.drop_column('payment_schedules', 'gateway_name')
    op.drop_column('payment_schedules', 'expected_date')
    op.drop_column('payment_schedules', 'assigned_user')
    op.drop_column('payment_schedules', 'erp_status')
    op.drop_column('payment_schedules', 'payment_method')
    op.drop_column('payment_schedules', 'risk_level')
    op.drop_column('payment_schedules', 'priority')
    op.drop_index(op.f('ix_invoices_assigned_reviewer_id'), table_name='invoices')
    op.alter_column('invoices', 'workflow_status',
               existing_type=sa.Enum('validation_pending', 'validation_failed', 'pending_review', 'pending_approval', 'approved', 'rejected', 'released_for_payment', 'paid', 'payment_queue', 'scheduled', 'payment_processing', 'payment_completed', name='invoiceworkflowstatus'),
               type_=sa.VARCHAR(length=18),
               existing_nullable=False)
    op.drop_column('invoices', 'review_duration_seconds')
    op.drop_column('invoices', 'reviewer_confidence_after')
    op.drop_column('invoices', 'reviewer_confidence_before')
    op.drop_column('invoices', 'reviewer_checklist_completed')
    op.create_table('gst_hsn_rules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('organization_id', sa.CHAR(length=32), nullable=True),
    sa.Column('hsn_prefix', sa.VARCHAR(), nullable=False),
    sa.Column('rule_type', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gst_hsn_rules_rule_type'), 'gst_hsn_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_gst_hsn_rules_organization_id'), 'gst_hsn_rules', ['organization_id'], unique=False)
    op.create_index(op.f('ix_gst_hsn_rules_id'), 'gst_hsn_rules', ['id'], unique=False)
    op.create_index(op.f('ix_gst_hsn_rules_hsn_prefix'), 'gst_hsn_rules', ['hsn_prefix'], unique=False)
    op.create_table('org_api_keys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('org_id', sa.CHAR(length=32), nullable=True),
    sa.Column('provider_name', sa.VARCHAR(), nullable=False),
    sa.Column('key_name', sa.VARCHAR(), nullable=False),
    sa.Column('encrypted_key', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('cooldown_until', sa.DATETIME(), nullable=True),
    sa.Column('priority_order', sa.INTEGER(), nullable=False),
    sa.Column('last_used_at', sa.DATETIME(), nullable=True),
    sa.Column('last_error', sa.VARCHAR(), nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_api_keys_provider_name'), 'org_api_keys', ['provider_name'], unique=False)
    op.create_index(op.f('ix_org_api_keys_org_id'), 'org_api_keys', ['org_id'], unique=False)
    op.create_index(op.f('ix_org_api_keys_id'), 'org_api_keys', ['id'], unique=False)
    op.create_table('erp_sync_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), nullable=False),
    sa.Column('erp_system', sa.VARCHAR(), nullable=False),
    sa.Column('sync_status', sa.VARCHAR(), nullable=False),
    sa.Column('sync_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('external_ref', sa.VARCHAR(), nullable=True),
    sa.Column('error_message', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_sync_logs_sync_status'), 'erp_sync_logs', ['sync_status'], unique=False)
    op.create_index(op.f('ix_erp_sync_logs_invoice_id'), 'erp_sync_logs', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_erp_sync_logs_id'), 'erp_sync_logs', ['id'], unique=False)
    op.create_index(op.f('ix_erp_sync_logs_erp_system'), 'erp_sync_logs', ['erp_system'], unique=False)
    op.drop_index(op.f('ix_payment_gateway_configs_name'), table_name='payment_gateway_configs')
    op.drop_index(op.f('ix_payment_gateway_configs_id'), table_name='payment_gateway_configs')
    op.drop_table('payment_gateway_configs')
    # ### end Alembic commands ###
