/**
 * AUTO-GENERATED FILE. DO NOT MODIFY DIRECTLY.
 * Generated by: backend/app/utils/generate_ts_types.py
 */

export enum InvoiceWorkflowStatus {
  validation_pending = "validation_pending",
  validation_failed = "validation_failed",
  pending_review = "pending_review",
  pending_approval = "pending_approval",
  approved = "approved",
  rejected = "rejected",
  released_for_payment = "released_for_payment",
  paid = "paid",
}

export enum PurchaseOrderStatus {
  open = "open",
  approved = "approved",
  closed = "closed",
}

export interface InvoiceItemCreate {
  item_number?: number | null;
  description?: string | null;
  quantity?: number;
  unit_price?: number;
  total_item_value?: number;
  hsn_code?: string | null;
  gst_rate?: number;
  assessable_value?: number;
  cgst_amount?: number;
  sgst_amount?: number;
  igst_amount?: number;
  sl_no?: string | null;
  is_service?: string;
  unit?: string | null;
  total_amount?: number;
  discount?: number;
  cess_rate?: number;
  cess_amount?: number;
  cess_non_advalorem_amount?: number;
  state_cess_rate?: number;
  state_cess_amount?: number;
  other_charges?: number;
}

export interface InvoiceItemResponse {
  item_number?: number | null;
  description?: string | null;
  quantity?: number;
  unit_price?: number;
  total_item_value?: number;
  hsn_code?: string | null;
  gst_rate?: number;
  assessable_value?: number;
  cgst_amount?: number;
  sgst_amount?: number;
  igst_amount?: number;
  sl_no?: string | null;
  is_service?: string;
  unit?: string | null;
  total_amount?: number;
  discount?: number;
  cess_rate?: number;
  cess_amount?: number;
  cess_non_advalorem_amount?: number;
  state_cess_rate?: number;
  state_cess_amount?: number;
  other_charges?: number;
  id: number;
  invoice_id: number;
}

export interface InvoiceCreate {
  type_of_invoice?: string;
  po_number?: string | null;
  invoice_number?: string | null;
  invoice_date?: string | null;
  seller_name?: string | null;
  seller_gstin?: string | null;
  buyer_name?: string | null;
  buyer_gstin?: string | null;
  shipping_name?: string | null;
  shipping_gstin?: string | null;
  total_taxable_value?: number;
  total_cgst_value?: number;
  total_sgst_value?: number;
  total_igst_value?: number;
  round_off_amount?: number;
  total_invoice_value?: number;
  irn?: string | null;
  seller_gstin_pincode?: number;
  buyer_gstin_pincode?: number;
  shipping_gstin_pincode?: number;
  total_gst_rate?: number;
  total_ces_value?: number;
  total_st_ces_value?: number;
  total_discount_value?: number;
  total_accessment_value?: number;
  workflow_status?: InvoiceWorkflowStatus | null;
  validation_status?: string;
  match_status?: string;
  validation_errors?: any | null;
  confidence_score?: number | null;
  source_type?: string;
  processed_at?: string | null;
  vendor_name?: string | null;
  due_date?: string | null;
  subtotal?: number | null;
  tax_amount?: number | null;
  total_amount?: number | null;
  currency?: string | null;
  status?: string;
  items?: InvoiceItemCreate[] | null;
}

export interface InvoiceUpdate {
  type_of_invoice?: string | null;
  irn?: string | null;
  po_number?: string | null;
  invoice_number?: string | null;
  invoice_date?: string | null;
  seller_name?: string | null;
  seller_gstin?: string | null;
  seller_gstin_pincode?: number | null;
  buyer_name?: string | null;
  buyer_gstin?: string | null;
  buyer_gstin_pincode?: number | null;
  shipping_name?: string | null;
  shipping_gstin?: string | null;
  shipping_gstin_pincode?: number | null;
  total_taxable_value?: number | null;
  total_gst_rate?: number | null;
  total_cgst_value?: number | null;
  total_sgst_value?: number | null;
  total_igst_value?: number | null;
  total_ces_value?: number | null;
  total_st_ces_value?: number | null;
  total_discount_value?: number | null;
  round_off_amount?: number | null;
  total_accessment_value?: number | null;
  total_invoice_value?: number | null;
  workflow_status?: InvoiceWorkflowStatus | null;
  validation_status?: string | null;
  match_status?: string | null;
  validation_errors?: any | null;
  confidence_score?: number | null;
  source_type?: string | null;
  processed_at?: string | null;
  vendor_name?: string | null;
  due_date?: string | null;
  subtotal?: number | null;
  tax_amount?: number | null;
  total_amount?: number | null;
  currency?: string | null;
  status?: string | null;
}

export interface InvoiceResponse {
  type_of_invoice?: string;
  po_number?: string | null;
  invoice_number?: string | null;
  invoice_date?: string | null;
  seller_name?: string | null;
  seller_gstin?: string | null;
  buyer_name?: string | null;
  buyer_gstin?: string | null;
  shipping_name?: string | null;
  shipping_gstin?: string | null;
  total_taxable_value?: number;
  total_cgst_value?: number;
  total_sgst_value?: number;
  total_igst_value?: number;
  round_off_amount?: number;
  total_invoice_value?: number;
  irn?: string | null;
  seller_gstin_pincode?: number;
  buyer_gstin_pincode?: number;
  shipping_gstin_pincode?: number;
  total_gst_rate?: number;
  total_ces_value?: number;
  total_st_ces_value?: number;
  total_discount_value?: number;
  total_accessment_value?: number;
  workflow_status?: InvoiceWorkflowStatus | null;
  validation_status?: string;
  match_status?: string;
  validation_errors?: any | null;
  confidence_score?: number | null;
  source_type?: string;
  processed_at?: string | null;
  vendor_name?: string | null;
  due_date?: string | null;
  subtotal?: number | null;
  tax_amount?: number | null;
  total_amount?: number | null;
  currency?: string | null;
  status?: string;
  id: number;
  items?: InvoiceItemResponse[];
}

export interface PurchaseOrderCreate {
  po_number: string;
  vendor_name: string;
  vendor_gstin?: string | null;
  po_amount: number;
  po_date: string;
  status?: string;
}

export interface PurchaseOrderUpdate {
  po_number?: string | null;
  vendor_name?: string | null;
  vendor_gstin?: string | null;
  po_amount?: number | null;
  po_date?: string | null;
  status?: string | null;
}

export interface PurchaseOrderResponse {
  po_number: string;
  vendor_name: string;
  vendor_gstin?: string | null;
  po_amount: number;
  po_date: string;
  status?: string;
  id: number;
}

export interface AuditLogCreate {
  invoice_id?: number | null;
  action: string;
  status_before?: string | null;
  status_after?: string | null;
  performed_by?: string;
  details?: any | null;
}

export interface AuditLogResponse {
  invoice_id?: number | null;
  action: string;
  status_before?: string | null;
  status_after?: string | null;
  performed_by?: string;
  details?: any | null;
  id: number;
  timestamp: string;
}
